from Classes.Enums import TyreCompound, Track, SafetyCarStatus, TrackCategory
import torch
import inspect
import numpy as np
from enum import Enum
from termcolor import colored
import pandas as pd

################################################################################
# AUTO-GENERATED FILE - DO NOT MODIFY #
# This file was automatically generated by the system.
# Any changes made to this file may be overwritten.
################################################################################

PRIMITIVE_TYPES = {int, float, bool}

class UnifiedRaceState:
    __slots__ = [
        "terminal",  # Is the state a terminal state
        "track",  # Track the state is on
        "track_category",  # Category of the track
        "year",  # Year of the race
        "safety_car",  # Status of the safety car
        "position",  # Position of the car
        "scaled_position",  # Scaled position of the car [0, 1]
        "pre_pitstop_position",  # Position of the car before the last pitstop
        "predicted_finish",  # Predicted finishing position of the car
        "partial_lap_number",  # Number of partial laps completed
        "race_progress",  # Percentage of the race completed
        "num_pitstops",  # Number of pit stops made
        "current_tyre",  # Current tyre compound
        "tyre_degradation",  # Current tyre degradation
        "scaled_tyre_degradation",  # Scaled tyre degradation [0, 1]
        "tyre_age",  # Current tyre age
        "stint_length",  # Length of the current stint
        "scaled_stint_length",  # Scaled length of the current stint [0, 1]
        "soft_available",  # Soft tyre available to pit onto
        "medium_available",  # Medium tyre available to pit onto
        "hard_available",  # Hard tyre available to pit onto
        "fuel",  # Current fuel level
        "fuel_consumption",  # Fuel consumption per lap
        "is_damaged",  # Is the car damaged
        "gap_ahead",  # Gap to the driver ahead
        "scaled_gap_ahead",  # Scaled gap to the driver ahead [-1, 1]
        "gap_behind",  # Gap to the driver behind
        "scaled_gap_behind",  # Scaled gap to the driver behind [-1, 1]
        "gap_to_leader",  # Gap to the leader
        "scaled_gap_to_leader",  # Scaled gap to the leader [-1, 1]
        "last_lap_time",  # Last lap time
        "reference_lap_time",  # Reference lap time
        "last_lap_to_reference",  # The ratio of the last lap time to the reference lap time
        "scaled_last_lap_to_reference",  # Scaled ratio of the last lap time to the reference lap time
        "valid_finish",  # Is the finish valid
        "__trainable_parameters",  # The trainable parameters of the UnifiedRaceState
        "__all_parameters",        # All parameters of the UnifiedRaceState
    ]

    def __init__(
        self,
        terminal: bool,
        track: Track,
        track_category: TrackCategory,
        year: int,
        safety_car: SafetyCarStatus,
        position: int,
        scaled_position: float,
        pre_pitstop_position: int,
        predicted_finish: int,
        partial_lap_number: float,
        race_progress: float,
        num_pitstops: int,
        current_tyre: TyreCompound,
        tyre_degradation: float,
        scaled_tyre_degradation: float,
        tyre_age: float,
        stint_length: float,
        scaled_stint_length: float,
        soft_available: bool,
        medium_available: bool,
        hard_available: bool,
        fuel: float,
        fuel_consumption: float,
        is_damaged: bool,
        gap_ahead: float,
        scaled_gap_ahead: float,
        gap_behind: float,
        scaled_gap_behind: float,
        gap_to_leader: float,
        scaled_gap_to_leader: float,
        last_lap_time: float,
        reference_lap_time: float,
        last_lap_to_reference: float,
        scaled_last_lap_to_reference: float,
        valid_finish: bool,
    ):
        self.terminal = terminal
        self.track = track
        self.track_category = track_category
        self.year = year
        self.safety_car = safety_car
        self.position = position
        self.scaled_position = scaled_position
        self.pre_pitstop_position = pre_pitstop_position
        self.predicted_finish = predicted_finish
        self.partial_lap_number = partial_lap_number
        self.race_progress = race_progress
        self.num_pitstops = num_pitstops
        self.current_tyre = current_tyre
        self.tyre_degradation = tyre_degradation
        self.scaled_tyre_degradation = scaled_tyre_degradation
        self.tyre_age = tyre_age
        self.stint_length = stint_length
        self.scaled_stint_length = scaled_stint_length
        self.soft_available = soft_available
        self.medium_available = medium_available
        self.hard_available = hard_available
        self.fuel = fuel
        self.fuel_consumption = fuel_consumption
        self.is_damaged = is_damaged
        self.gap_ahead = gap_ahead
        self.scaled_gap_ahead = scaled_gap_ahead
        self.gap_behind = gap_behind
        self.scaled_gap_behind = scaled_gap_behind
        self.gap_to_leader = gap_to_leader
        self.scaled_gap_to_leader = scaled_gap_to_leader
        self.last_lap_time = last_lap_time
        self.reference_lap_time = reference_lap_time
        self.last_lap_to_reference = last_lap_to_reference
        self.scaled_last_lap_to_reference = scaled_last_lap_to_reference
        self.valid_finish = valid_finish
        self.__trainable_parameters = [
            "safety_car",
            "scaled_position",
            "race_progress",
            "current_tyre",
            "scaled_tyre_degradation",
            "soft_available",
            "medium_available",
            "hard_available",
            "scaled_gap_ahead",
            "scaled_gap_behind",
            "scaled_gap_to_leader",
            "last_lap_to_reference",
            "valid_finish",
        ]
        self.__all_parameters = [
            "terminal",
            "track",
            "track_category",
            "year",
            "safety_car",
            "position",
            "scaled_position",
            "pre_pitstop_position",
            "predicted_finish",
            "partial_lap_number",
            "race_progress",
            "num_pitstops",
            "current_tyre",
            "tyre_degradation",
            "scaled_tyre_degradation",
            "tyre_age",
            "stint_length",
            "scaled_stint_length",
            "soft_available",
            "medium_available",
            "hard_available",
            "fuel",
            "fuel_consumption",
            "is_damaged",
            "gap_ahead",
            "scaled_gap_ahead",
            "gap_behind",
            "scaled_gap_behind",
            "gap_to_leader",
            "scaled_gap_to_leader",
            "last_lap_time",
            "reference_lap_time",
            "last_lap_to_reference",
            "scaled_last_lap_to_reference",
            "valid_finish",
        ]

    def __str__(self) -> str:
        s = "UnifiedRaceState["
        s += f"{'T' if self.terminal else 'R'} " 
        s += f"{self.track} " 
        s += f"{self.track_category:<4} " 
        s += f"{self.year} " 
        s += colored(f"{self.safety_car} ", "blue") 
        s += f"P{self.position:<2} " 
        s += colored(f"SP{self.scaled_position:<6.3f} ", "blue") 
        s += f"PP{self.pre_pitstop_position:<2} " 
        s += f"PF{self.predicted_finish:<2} " 
        s += f"L{self.partial_lap_number:<5.2f} " 
        s += colored(f"L%{int(self.race_progress*100):<3} ", "blue") 
        s += f"PS{self.num_pitstops:<2} " 
        s += colored(f"{str(self.current_tyre)[0]} ", "blue") 
        s += f"TD{self.tyre_degradation:<6.3f} " 
        s += colored(f"STD{self.scaled_tyre_degradation:<6.3f} ", "blue") 
        s += f"T%{int(self.tyre_age*100):<3} " 
        s += f"SL{self.stint_length:<4.1f} " 
        s += f"SSL{self.scaled_stint_length:<6.3f} " 
        s += colored(f"{'[S]' if self.soft_available else '[ ]'} ", "blue") 
        s += colored(f"{'[M]' if self.medium_available else '[ ]'} ", "blue") 
        s += colored(f"{'[H]' if self.hard_available else '[ ]'} ", "blue") 
        s += f"F{self.fuel:<7.3f} " 
        s += f"FC{self.fuel_consumption:<6.3f} " 
        s += f"{' D' if self.is_damaged else 'ND'} " 
        s += f"GA{self.gap_ahead:<7.3f} " 
        s += colored(f"SGA{self.scaled_gap_ahead:<6.3f} ", "blue") 
        s += f"GB{self.gap_behind:<7.3f} " 
        s += colored(f"SGB{self.scaled_gap_behind:<6.3f} ", "blue") 
        s += f"GL{self.gap_to_leader:<7.3f} " 
        s += colored(f"SGL{self.scaled_gap_to_leader:<6.3f} ", "blue") 
        s += f"LL{self.last_lap_time:<7.3f}  " 
        s += f"RL{self.reference_lap_time:<7.3f} " 
        s += colored(f"LT%{int(self.last_lap_to_reference*100):<3} ", "blue") 
        s += f"SLT{self.scaled_last_lap_to_reference:<3.2f} " 
        s += colored(f"{' V' if self.valid_finish else 'NV'} ", "blue") 
        s += "]"
        return s

    def to_tensor(self) -> torch.Tensor:
        attribute_values = [
            getattr(self, attr)
            for attr in self.__trainable_parameters
        ]

        # Convert non-numeric attributes to appropriate tensor type
        converted_values = []
        for value in attribute_values:
            if isinstance(value, (int, float, bool, np.bool_)):
                converted_values.append(value)

            elif isinstance(value, Enum):
                one_hot = [0] * len(value.__class__)
                one_hot[value.value] = 1
                converted_values.extend(one_hot)
            else:
                raise ValueError(f"Unsupported attribute type: {type(value)}, {value}")

        return torch.tensor(converted_values, dtype=torch.float32)

    def all_to_tensor(self) -> torch.Tensor:
        attribute_values = [
            getattr(self, attr)
            for attr in self.__all_parameters
        ]

        # Convert non-numeric attributes to appropriate tensor type
        converted_values = []
        for value in attribute_values:
            if isinstance(value, (int, float, bool, np.bool_)):
                converted_values.append(value)

            elif isinstance(value, Enum):
                one_hot = [0] * len(value.__class__)
                one_hot[value.value] = 1
                converted_values.extend(one_hot)
            else:
                raise ValueError(f"Unsupported attribute type: {type(value)}, {value}")

        return torch.tensor(converted_values, dtype=torch.float32)

    def to_list(self) -> list:
        return [
            self.safety_car,
            self.scaled_position,
            self.race_progress,
            self.current_tyre,
            self.scaled_tyre_degradation,
            self.soft_available,
            self.medium_available,
            self.hard_available,
            self.scaled_gap_ahead,
            self.scaled_gap_behind,
            self.scaled_gap_to_leader,
            self.last_lap_to_reference,
            self.valid_finish,
        ]

    def all_to_list(self) -> list:
        return [
            self.terminal,
            self.track,
            self.track_category,
            self.year,
            self.safety_car,
            self.position,
            self.scaled_position,
            self.pre_pitstop_position,
            self.predicted_finish,
            self.partial_lap_number,
            self.race_progress,
            self.num_pitstops,
            self.current_tyre,
            self.tyre_degradation,
            self.scaled_tyre_degradation,
            self.tyre_age,
            self.stint_length,
            self.scaled_stint_length,
            self.soft_available,
            self.medium_available,
            self.hard_available,
            self.fuel,
            self.fuel_consumption,
            self.is_damaged,
            self.gap_ahead,
            self.scaled_gap_ahead,
            self.gap_behind,
            self.scaled_gap_behind,
            self.gap_to_leader,
            self.scaled_gap_to_leader,
            self.last_lap_time,
            self.reference_lap_time,
            self.last_lap_to_reference,
            self.scaled_last_lap_to_reference,
            self.valid_finish,
        ]

    def to_dataframe(self) -> pd.DataFrame:
        return pd.DataFrame([self.to_list()], columns=self.get_feature_names())

    def all_to_dataframe(self) -> pd.DataFrame:
        return pd.DataFrame([self.all_to_list()], columns=self.get_all_feature_names())

    ############################################################################
    # Static Methods
    ############################################################################
   
    @staticmethod    
    def to_dataframe(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        return pd.DataFrame(
            [state.to_list() for state in states],
            columns=UnifiedRaceState.get_feature_names()
        )
    
    @staticmethod
    def to_dataframe_no_scaled(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        y = UnifiedRaceState.to_all_dataframe(states)
        x = UnifiedRaceState.to_dataframe(states)
        scaled_columns = [col for col in x.columns if "Scaled" in col]
        unscaled_columns = [col.replace("Scaled ", "") for col in scaled_columns]
        # Get the unscaled columns
        z = y[unscaled_columns]
        # Drop the scaled columns
        x = x.drop(columns=scaled_columns)
        # Concatenate the two dataframes
        return pd.concat([x, z], axis=1)

    @staticmethod
    def to_all_dataframe(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        return pd.DataFrame(
            [state.all_to_list() for state in states],
            columns=UnifiedRaceState.get_all_feature_names()
        )

    @staticmethod
    def to_all_dataframe_no_scaled(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        x = UnifiedRaceState.to_all_dataframe(states)
        scaled_columns = [col for col in x.columns if "Scaled" in col]
        return x.drop(columns=scaled_columns)

    @staticmethod
    def to_tensor_dataframe(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        return pd.DataFrame(
            [state.to_tensor().numpy() for state in states],
            columns=UnifiedRaceState.get_tensor_feature_names()
        )

    @staticmethod
    def to_tensor_dataframe_no_scaled(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        y = UnifiedRaceState.to_all_tensor_dataframe(states)
        x = UnifiedRaceState.to_tensor_dataframe(states)
        scaled_columns = [col for col in x.columns if "Scaled" in col]
        unscaled_columns = [col.replace("Scaled ", "") for col in scaled_columns]
        # Get the unscaled columns
        z = y[unscaled_columns]
        # Drop the scaled columns
        x = x.drop(columns=scaled_columns)
        # Concatenate the two dataframes
        return pd.concat([x, z], axis=1)

    @staticmethod
    def to_all_tensor_dataframe(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        return pd.DataFrame(
            [state.all_to_tensor().numpy() for state in states],
            columns=UnifiedRaceState.get_all_tensor_feature_names()
        )

    @staticmethod
    def to_all_tensor_dataframe_no_scaled(states: list["UnifiedRaceState"]) -> pd.DataFrame:
        x = UnifiedRaceState.to_all_tensor_dataframe(states)
        scaled_columns = [col for col in x.columns if "Scaled" in col]
        return x.drop(columns=scaled_columns)
    
    @staticmethod
    def from_dataframe_to_tensor(df: pd.DataFrame):
        tensors = []
        for _, row in df.iterrows():
            urs = UnifiedRaceState(
                terminal=None,
                track=None,
                track_category=None,
                year=None,
                safety_car=SafetyCarStatus(row["safety_car".replace("_", " ").title()]),
                position=None,
                scaled_position=float(row["scaled_position".replace("_", " ").title()]),
                pre_pitstop_position=None,
                predicted_finish=None,
                partial_lap_number=None,
                race_progress=float(row["race_progress".replace("_", " ").title()]),
                num_pitstops=None,
                current_tyre=TyreCompound(row["current_tyre".replace("_", " ").title()]),
                tyre_degradation=None,
                scaled_tyre_degradation=float(row["scaled_tyre_degradation".replace("_", " ").title()]),
                tyre_age=None,
                stint_length=None,
                scaled_stint_length=None,
                soft_available=bool(row["soft_available".replace("_", " ").title()]),
                medium_available=bool(row["medium_available".replace("_", " ").title()]),
                hard_available=bool(row["hard_available".replace("_", " ").title()]),
                fuel=None,
                fuel_consumption=None,
                is_damaged=None,
                gap_ahead=None,
                scaled_gap_ahead=float(row["scaled_gap_ahead".replace("_", " ").title()]),
                gap_behind=None,
                scaled_gap_behind=float(row["scaled_gap_behind".replace("_", " ").title()]),
                gap_to_leader=None,
                scaled_gap_to_leader=float(row["scaled_gap_to_leader".replace("_", " ").title()]),
                last_lap_time=None,
                reference_lap_time=None,
                last_lap_to_reference=float(row["last_lap_to_reference".replace("_", " ").title()]),
                scaled_last_lap_to_reference=None,
                valid_finish=bool(row["valid_finish".replace("_", " ").title()]),
            )

            tensors.append(urs.to_tensor())
        
        return torch.stack(tensors)

    @staticmethod
    def size() -> int:
        # The input shape of the class, converted to a tensor
        # We iterate over all trainable parameters and get the length of their type
        # Enums are one-hot encoded

        t = 0

        # For safety_car
        t += 1 if SafetyCarStatus in PRIMITIVE_TYPES else len(SafetyCarStatus)

        # For scaled_position
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For race_progress
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For current_tyre
        t += 1 if TyreCompound in PRIMITIVE_TYPES else len(TyreCompound)

        # For scaled_tyre_degradation
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For soft_available
        t += 1 if bool in PRIMITIVE_TYPES else len(bool)

        # For medium_available
        t += 1 if bool in PRIMITIVE_TYPES else len(bool)

        # For hard_available
        t += 1 if bool in PRIMITIVE_TYPES else len(bool)

        # For scaled_gap_ahead
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For scaled_gap_behind
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For scaled_gap_to_leader
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For last_lap_to_reference
        t += 1 if float in PRIMITIVE_TYPES else len(float)

        # For valid_finish
        t += 1 if bool in PRIMITIVE_TYPES else len(bool)

        return t

    @staticmethod
    def get_feature_names() -> list[str]:        
        return [
            "safety_car".replace("_", " ").title(),
            "scaled_position".replace("_", " ").title(),
            "race_progress".replace("_", " ").title(),
            "current_tyre".replace("_", " ").title(),
            "scaled_tyre_degradation".replace("_", " ").title(),
            "soft_available".replace("_", " ").title(),
            "medium_available".replace("_", " ").title(),
            "hard_available".replace("_", " ").title(),
            "scaled_gap_ahead".replace("_", " ").title(),
            "scaled_gap_behind".replace("_", " ").title(),
            "scaled_gap_to_leader".replace("_", " ").title(),
            "last_lap_to_reference".replace("_", " ").title(),
            "valid_finish".replace("_", " ").title(),
        ]

    @staticmethod
    def get_all_feature_names() -> list[str]:
        return [
            "terminal".replace("_", " ").title(),
            "track".replace("_", " ").title(),
            "track_category".replace("_", " ").title(),
            "year".replace("_", " ").title(),
            "safety_car".replace("_", " ").title(),
            "position".replace("_", " ").title(),
            "scaled_position".replace("_", " ").title(),
            "pre_pitstop_position".replace("_", " ").title(),
            "predicted_finish".replace("_", " ").title(),
            "partial_lap_number".replace("_", " ").title(),
            "race_progress".replace("_", " ").title(),
            "num_pitstops".replace("_", " ").title(),
            "current_tyre".replace("_", " ").title(),
            "tyre_degradation".replace("_", " ").title(),
            "scaled_tyre_degradation".replace("_", " ").title(),
            "tyre_age".replace("_", " ").title(),
            "stint_length".replace("_", " ").title(),
            "scaled_stint_length".replace("_", " ").title(),
            "soft_available".replace("_", " ").title(),
            "medium_available".replace("_", " ").title(),
            "hard_available".replace("_", " ").title(),
            "fuel".replace("_", " ").title(),
            "fuel_consumption".replace("_", " ").title(),
            "is_damaged".replace("_", " ").title(),
            "gap_ahead".replace("_", " ").title(),
            "scaled_gap_ahead".replace("_", " ").title(),
            "gap_behind".replace("_", " ").title(),
            "scaled_gap_behind".replace("_", " ").title(),
            "gap_to_leader".replace("_", " ").title(),
            "scaled_gap_to_leader".replace("_", " ").title(),
            "last_lap_time".replace("_", " ").title(),
            "reference_lap_time".replace("_", " ").title(),
            "last_lap_to_reference".replace("_", " ").title(),
            "scaled_last_lap_to_reference".replace("_", " ").title(),
            "valid_finish".replace("_", " ").title(),
        ]

    @staticmethod
    def get_continuous_feature_names() -> list[str]:
        return [
            "scaled_position".replace("_", " ").title(),
            "race_progress".replace("_", " ").title(),
            "scaled_tyre_degradation".replace("_", " ").title(),
            "scaled_gap_ahead".replace("_", " ").title(),
            "scaled_gap_behind".replace("_", " ").title(),
            "scaled_gap_to_leader".replace("_", " ").title(),
            "last_lap_to_reference".replace("_", " ").title(),
        ]

    @staticmethod
    def get_all_continuous_feature_names() -> list[str]:
        return [
            "scaled_position".replace("_", " ").title(),
            "partial_lap_number".replace("_", " ").title(),
            "race_progress".replace("_", " ").title(),
            "tyre_degradation".replace("_", " ").title(),
            "scaled_tyre_degradation".replace("_", " ").title(),
            "tyre_age".replace("_", " ").title(),
            "scaled_stint_length".replace("_", " ").title(),
            "fuel".replace("_", " ").title(),
            "fuel_consumption".replace("_", " ").title(),
            "gap_ahead".replace("_", " ").title(),
            "scaled_gap_ahead".replace("_", " ").title(),
            "gap_behind".replace("_", " ").title(),
            "scaled_gap_behind".replace("_", " ").title(),
            "gap_to_leader".replace("_", " ").title(),
            "scaled_gap_to_leader".replace("_", " ").title(),
            "last_lap_time".replace("_", " ").title(),
            "reference_lap_time".replace("_", " ").title(),
            "last_lap_to_reference".replace("_", " ").title(),
            "scaled_last_lap_to_reference".replace("_", " ").title(),
        ]
    @staticmethod
    def get_ordinal_feature_names() -> list[str]:
        return [
        ]
    
    @staticmethod
    def get_all_ordinal_feature_names() -> list[str]:
        return [
            "year".replace("_", " ").title(),
            "position".replace("_", " ").title(),
            "pre_pitstop_position".replace("_", " ").title(),
            "predicted_finish".replace("_", " ").title(),
            "num_pitstops".replace("_", " ").title(),
            "stint_length".replace("_", " ").title(),
        ]

    @staticmethod
    def get_categorical_feature_names() -> list[str]:
        return [
            "safety_car".replace("_", " ").title(),
            "current_tyre".replace("_", " ").title(),
            "soft_available".replace("_", " ").title(),
            "medium_available".replace("_", " ").title(),
            "hard_available".replace("_", " ").title(),
            "valid_finish".replace("_", " ").title(),
        ]
    
    @staticmethod
    def get_all_categorical_feature_names() -> list[str]:
        return [
            "terminal".replace("_", " ").title(),
            "track".replace("_", " ").title(),
            "track_category".replace("_", " ").title(),
            "safety_car".replace("_", " ").title(),
            "current_tyre".replace("_", " ").title(),
            "soft_available".replace("_", " ").title(),
            "medium_available".replace("_", " ").title(),
            "hard_available".replace("_", " ").title(),
            "is_damaged".replace("_", " ").title(),
            "valid_finish".replace("_", " ").title(),
        ]

    @staticmethod
    def get_tensor_feature_names() -> list[str]:
        feature_names = []

        # For safety_car
        if SafetyCarStatus not in PRIMITIVE_TYPES:
            for val in SafetyCarStatus:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("safety_car".replace("_", " ").title())

        # For scaled_position
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_position".replace("_", " ").title())

        # For race_progress
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("race_progress".replace("_", " ").title())

        # For current_tyre
        if TyreCompound not in PRIMITIVE_TYPES:
            for val in TyreCompound:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("current_tyre".replace("_", " ").title())

        # For scaled_tyre_degradation
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_tyre_degradation".replace("_", " ").title())

        # For soft_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("soft_available".replace("_", " ").title())

        # For medium_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("medium_available".replace("_", " ").title())

        # For hard_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("hard_available".replace("_", " ").title())

        # For scaled_gap_ahead
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_ahead".replace("_", " ").title())

        # For scaled_gap_behind
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_behind".replace("_", " ").title())

        # For scaled_gap_to_leader
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_to_leader".replace("_", " ").title())

        # For last_lap_to_reference
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("last_lap_to_reference".replace("_", " ").title())

        # For valid_finish
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("valid_finish".replace("_", " ").title())


        return feature_names

    @staticmethod
    def get_all_tensor_feature_names() -> list[str]:
        feature_names = []

        # For terminal
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("terminal".replace("_", " ").title())

        # For track
        if Track not in PRIMITIVE_TYPES:
            for val in Track:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("track".replace("_", " ").title())

        # For track_category
        if TrackCategory not in PRIMITIVE_TYPES:
            for val in TrackCategory:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("track_category".replace("_", " ").title())

        # For year
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("year".replace("_", " ").title())

        # For safety_car
        if SafetyCarStatus not in PRIMITIVE_TYPES:
            for val in SafetyCarStatus:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("safety_car".replace("_", " ").title())

        # For position
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("position".replace("_", " ").title())

        # For scaled_position
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_position".replace("_", " ").title())

        # For pre_pitstop_position
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("pre_pitstop_position".replace("_", " ").title())

        # For predicted_finish
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("predicted_finish".replace("_", " ").title())

        # For partial_lap_number
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("partial_lap_number".replace("_", " ").title())

        # For race_progress
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("race_progress".replace("_", " ").title())

        # For num_pitstops
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("num_pitstops".replace("_", " ").title())

        # For current_tyre
        if TyreCompound not in PRIMITIVE_TYPES:
            for val in TyreCompound:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("current_tyre".replace("_", " ").title())

        # For tyre_degradation
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("tyre_degradation".replace("_", " ").title())

        # For scaled_tyre_degradation
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_tyre_degradation".replace("_", " ").title())

        # For tyre_age
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("tyre_age".replace("_", " ").title())

        # For stint_length
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("stint_length".replace("_", " ").title())

        # For scaled_stint_length
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_stint_length".replace("_", " ").title())

        # For soft_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("soft_available".replace("_", " ").title())

        # For medium_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("medium_available".replace("_", " ").title())

        # For hard_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("hard_available".replace("_", " ").title())

        # For fuel
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("fuel".replace("_", " ").title())

        # For fuel_consumption
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("fuel_consumption".replace("_", " ").title())

        # For is_damaged
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("is_damaged".replace("_", " ").title())

        # For gap_ahead
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("gap_ahead".replace("_", " ").title())

        # For scaled_gap_ahead
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_ahead".replace("_", " ").title())

        # For gap_behind
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("gap_behind".replace("_", " ").title())

        # For scaled_gap_behind
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_behind".replace("_", " ").title())

        # For gap_to_leader
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("gap_to_leader".replace("_", " ").title())

        # For scaled_gap_to_leader
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_to_leader".replace("_", " ").title())

        # For last_lap_time
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("last_lap_time".replace("_", " ").title())

        # For reference_lap_time
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("reference_lap_time".replace("_", " ").title())

        # For last_lap_to_reference
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("last_lap_to_reference".replace("_", " ").title())

        # For scaled_last_lap_to_reference
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_last_lap_to_reference".replace("_", " ").title())

        # For valid_finish
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("valid_finish".replace("_", " ").title())


        return feature_names

    @staticmethod
    def get_continuous_tensor_feature_names() -> list[str]:
        feature_names = []

        # For scaled_position
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_position".replace("_", " ").title())
        # For race_progress
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("race_progress".replace("_", " ").title())
        # For scaled_tyre_degradation
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_tyre_degradation".replace("_", " ").title())
        # For scaled_gap_ahead
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_ahead".replace("_", " ").title())
        # For scaled_gap_behind
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_behind".replace("_", " ").title())
        # For scaled_gap_to_leader
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_to_leader".replace("_", " ").title())
        # For last_lap_to_reference
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("last_lap_to_reference".replace("_", " ").title())

        return feature_names

    @staticmethod
    def get_all_continuous_tensor_feature_names() -> list[str]:
        feature_names = []

        # For scaled_position
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_position".replace("_", " ").title())
        # For partial_lap_number
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("partial_lap_number".replace("_", " ").title())
        # For race_progress
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("race_progress".replace("_", " ").title())
        # For tyre_degradation
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("tyre_degradation".replace("_", " ").title())
        # For scaled_tyre_degradation
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_tyre_degradation".replace("_", " ").title())
        # For tyre_age
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("tyre_age".replace("_", " ").title())
        # For scaled_stint_length
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_stint_length".replace("_", " ").title())
        # For fuel
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("fuel".replace("_", " ").title())
        # For fuel_consumption
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("fuel_consumption".replace("_", " ").title())
        # For gap_ahead
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("gap_ahead".replace("_", " ").title())
        # For scaled_gap_ahead
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_ahead".replace("_", " ").title())
        # For gap_behind
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("gap_behind".replace("_", " ").title())
        # For scaled_gap_behind
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_behind".replace("_", " ").title())
        # For gap_to_leader
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("gap_to_leader".replace("_", " ").title())
        # For scaled_gap_to_leader
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_gap_to_leader".replace("_", " ").title())
        # For last_lap_time
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("last_lap_time".replace("_", " ").title())
        # For reference_lap_time
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("reference_lap_time".replace("_", " ").title())
        # For last_lap_to_reference
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("last_lap_to_reference".replace("_", " ").title())
        # For scaled_last_lap_to_reference
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("scaled_last_lap_to_reference".replace("_", " ").title())

        return feature_names

    @staticmethod
    def get_ordinal_tensor_feature_names() -> list[str]:
        feature_names = []


        return feature_names
    
    @staticmethod
    def get_all_ordinal_tensor_feature_names() -> list[str]:
        feature_names = []

        # For year
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("year".replace("_", " ").title())
        # For position
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("position".replace("_", " ").title())
        # For pre_pitstop_position
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("pre_pitstop_position".replace("_", " ").title())
        # For predicted_finish
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("predicted_finish".replace("_", " ").title())
        # For num_pitstops
        if int not in PRIMITIVE_TYPES:
            for val in int:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("num_pitstops".replace("_", " ").title())
        # For stint_length
        if float not in PRIMITIVE_TYPES:
            for val in float:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("stint_length".replace("_", " ").title())

        return feature_names

    @staticmethod
    def get_categorical_tensor_feature_names() -> list[str]:
        feature_names = []

        # For safety_car
        if SafetyCarStatus not in PRIMITIVE_TYPES:
            for val in SafetyCarStatus:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("safety_car".replace("_", " ").title())
        # For current_tyre
        if TyreCompound not in PRIMITIVE_TYPES:
            for val in TyreCompound:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("current_tyre".replace("_", " ").title())
        # For soft_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("soft_available".replace("_", " ").title())
        # For medium_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("medium_available".replace("_", " ").title())
        # For hard_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("hard_available".replace("_", " ").title())
        # For valid_finish
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("valid_finish".replace("_", " ").title())

        return feature_names
    
    @staticmethod
    def get_all_categorical_tensor_feature_names() -> list[str]:
        feature_names = []

        # For terminal
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("terminal".replace("_", " ").title())
        # For track
        if Track not in PRIMITIVE_TYPES:
            for val in Track:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("track".replace("_", " ").title())
        # For track_category
        if TrackCategory not in PRIMITIVE_TYPES:
            for val in TrackCategory:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("track_category".replace("_", " ").title())
        # For safety_car
        if SafetyCarStatus not in PRIMITIVE_TYPES:
            for val in SafetyCarStatus:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("safety_car".replace("_", " ").title())
        # For current_tyre
        if TyreCompound not in PRIMITIVE_TYPES:
            for val in TyreCompound:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("current_tyre".replace("_", " ").title())
        # For soft_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("soft_available".replace("_", " ").title())
        # For medium_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("medium_available".replace("_", " ").title())
        # For hard_available
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("hard_available".replace("_", " ").title())
        # For is_damaged
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("is_damaged".replace("_", " ").title())
        # For valid_finish
        if bool not in PRIMITIVE_TYPES:
            for val in bool:
                feature_names.append(val.name.replace("_", " ").title())
        else:
            feature_names.append("valid_finish".replace("_", " ").title())

        return feature_names

    @staticmethod
    def get_continuous_feature_bounds() -> dict[str, tuple[float, float]]:
        return {
            "scaled_position".replace("_", " ").title(): (0, 1),
            "partial_lap_number".replace("_", " ").title(): (0, 100),
            "race_progress".replace("_", " ").title(): (0, 1),
            "tyre_degradation".replace("_", " ").title(): (0, 100),
            "scaled_tyre_degradation".replace("_", " ").title(): (0, 1),
            "tyre_age".replace("_", " ").title(): (0, 100),
            "scaled_stint_length".replace("_", " ").title(): (0, 1),
            "fuel".replace("_", " ").title(): (0, 110),
            "fuel_consumption".replace("_", " ").title(): (0, 10),
            "gap_ahead".replace("_", " ").title(): (-1000, 1000),
            "scaled_gap_ahead".replace("_", " ").title(): (-1, 1),
            "gap_behind".replace("_", " ").title(): (-1000, 1000),
            "scaled_gap_behind".replace("_", " ").title(): (-1, 1),
            "gap_to_leader".replace("_", " ").title(): (-1000, 1000),
            "scaled_gap_to_leader".replace("_", " ").title(): (-1, 1),
            "last_lap_time".replace("_", " ").title(): (50, 180),
            "reference_lap_time".replace("_", " ").title(): (50, 180),
            "last_lap_to_reference".replace("_", " ").title(): (0, 2),
            "scaled_last_lap_to_reference".replace("_", " ").title(): (0, 1),
        }

    @staticmethod
    def get_ordinal_feature_values() -> dict[str, list[any]]:
        return {
            "year".replace("_", " ").title(): list(range(2021, 2023+1, 1)),
            "position".replace("_", " ").title(): list(range(1, 20+1, 1)),
            "pre_pitstop_position".replace("_", " ").title(): list(range(1, 20+1, 1)),
            "predicted_finish".replace("_", " ").title(): list(range(1, 20+1, 1)),
            "num_pitstops".replace("_", " ").title(): list(range(1, 10+1, 1)),
            "stint_length".replace("_", " ").title(): list(range(0, 100+1, 1)),
        }

    @staticmethod
    def get_categorical_feature_values() -> dict[str, list[any]]:
        feature_values = {}
        
        if bool == bool:
            feature_values["terminal".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["terminal".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in bool]

        if Track == bool:
            feature_values["track".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["track".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in Track]

        if TrackCategory == bool:
            feature_values["track_category".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["track_category".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in TrackCategory]

        if SafetyCarStatus == bool:
            feature_values["safety_car".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["safety_car".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in SafetyCarStatus]

        if TyreCompound == bool:
            feature_values["current_tyre".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["current_tyre".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in TyreCompound]

        if bool == bool:
            feature_values["soft_available".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["soft_available".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in bool]

        if bool == bool:
            feature_values["medium_available".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["medium_available".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in bool]

        if bool == bool:
            feature_values["hard_available".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["hard_available".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in bool]

        if bool == bool:
            feature_values["is_damaged".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["is_damaged".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in bool]

        if bool == bool:
            feature_values["valid_finish".replace("_", " ").title()] = ["True", "False"]
        else:
            feature_values["valid_finish".replace("_", " ").title()] = [val.name.replace("_", " ").title() for val in bool]


        return feature_values