DARK_BACKGROUND_COLOUR = "#3E3E3E"
LIGHT_BACKGROUND_COLOUR = "#FFFFFF"

PRIMARY_COLOUR = "#ADE1E5"
SECONDARY_COLOUR = "#F9C94D"
SECONDARY_TERTIARY_COLOUR = "#FC994A"
TERTIARY_COLOUR = "#FF6947"

DARK_PRIMARY_COLOUR = "#22686D"
DARK_SECONDARY_COLOUR = "#BF9000"
DARK_SECONDARY_TERTIARY_COLOUR = "#B45F06"
DARK_TERTIARY_COLOUR = "#A31E00"

LIGHT_TEXT_COLOUR = "#FFFFFF"
DARK_TEXT_COLOUR = "#000000"


SOFT_TYRE_COLOUR = "#DA291C"
MEDIUM_TYRE_COLOUR = "#FFD12E"
HARD_TYRE_COLOUR = "#F0F0EC"
INTERMEDIATE_TYRE_COLOUR = "#43B02A"
WET_TYRE_COLOUR = "#0067AD"

FSC_COLOUR = "#FFCF00"
VSC_COLOUR = "#9448BC"